Repository Noiztbander/php-employee-management-v1, pull requests merged in 2021-07, with the labels that each got.

#5 feat: created Dashboard employees list and merged with good first iss…
  assets/css/main.css
  assets/html/footer.html
  assets/js/grid_dates.js
  assets/js/index.js
  index.php
  resources/employees.json
  src/dashboard.php
  src/employee.php
  src/library/employeeController.php
  src/library/employeeManager.php
Labels: enhancement

#6 Feat 04/edit and update new employee
  assets/js/index.js
  index.php
  resources/employees.json
  src/dashboard.php
  src/employee.php
  src/library/employeeController.php
  src/library/employeeManager.php
Labels: enhancement

#8 feat:delete employees and fixed some bugs in updating process
  .gitignore
  assets/js/index.js
  resources/employees.json
  src/library/employeeController.php
  src/library/employeeManager.php
Labels: bug, enhancement

#10 Feat/09 control session timeout
  src/dashboard.php
  src/employee.php
  src/library/loginController.php
  src/library/sessionHelper.php
Labels: enhancement

#12 feat: clean code and add images carrousel
  assets/css/main.css
  assets/js/index.js
  index.php
  resources/employees.json
  src/employee.php
  src/library/avatarsApi.php
  src/library/employeeController.php
  src/library/employeeManager.php
  src/library/loginController.php
Labels: documentation, enhancement
